version: "2"
services:
    service-a:
        labels:
            com.microsoft.azure.acs.dcos.healthcheck: true
            HAPROXY_GROUP: "external"
            HAPROXY_0_VHOST: "bikesharingagents.southcentralus.cloudapp.azure.com"
